### ISSUE TITLE
corner case in native library loading code on windows

### ISSUE THREAD

**Issue by krgn** [zeromq/clrzmq4#85] opened 2017-01-26 17:16 UTC
Hi,

I am developing a plugin for a system that dynamically loads `.dlls` on startup as plugins called [VVVV](http://vvvv.org) and I have found a rather unfortunate corner case in the native `.dll` loading code that prevents me from shipping my plugin in a stand-alone fashion, packaging the native `ZeroMQ` libraries next to my managed libraries.

The scenario is the following:

* `vvvv.exe` (the main application) is located in `C:\Program Files\vvvv\vvvv_50alpha35.1_x64\`
* my plugin and the respective native libraries reside somewhere else on disk, e.g. `E:\src\projects\myplug` with the correct `amd64` sub-folder containing the native library
* as `vvvv.exe` starts up (having my plugin's location added to its search path), it tries to instantiate my plugin, which in turns attempts to load the native code from disk [as seen here](https://github.com/zeromq/clrzmq4/blob/master/lib/Platform.Win32.cs)

The actual computed search paths for this setup are: 

* `C:\Program Files\vvvv\vvvv_50alpha35.1_x64\amd64\libzmq.dll`
* `C:\Program Files\vvvv\vvvv_50alpha35.1_x64\x64\libzmq.dll`
* `C:\Windows\system32\libzmq.dll`

Observed behavior: 

[LoadUnmanagedLibrary](https://github.com/zeromq/clrzmq4/blob/master/lib/Platform.Win32.cs) currently looks in the system-wide location for the library, as well as the folder containing the application loading the plugin and thus fails to load my plugin due to the missing native code.

Desired behavior: 

[LoadUnmanagedLibrary](https://github.com/zeromq/clrzmq4/blob/master/lib/Platform.Win32.cs) should also include the folder containing the loaded `.dll`, e.g. in my case `E:\src\projects\myplug\amd64\libzmq.dll` and `E:\src\projects\myplug\x64\libzmq.dll` in its search path.

Is there any way I achieve the desired behavior by overriding the dll-loading behavior? It is not possible for me to ship the library with the main application `vvvv.exe` or to expect the user to have the library installed globally, and I guess it could be good to cover this corner case for other users too.

Thanks!

Karsten

**Comment by krgn** [comment] 2017-01-27 14:41
I made some experiments to see if it would be possible to add the currently executing assembly's path to the search path list by calling `Assembly.GetExecutingAssembly().Location` and it should work. Would a PR to that effect be of interest to the project?

**Comment by metadings** [comment] 2017-01-27 15:13
>  Would a PR to that effect be of interest to the project?

Yes :-)

There was also an issue of running ZeroMQ using ASP.NET... You should also try `AppDomain.CurrentDomain.DynamicDirectory`. Probably you just need to do

	Platform.ExpandPaths(libraryPaths, "{AppBase}", EnsureNotEndingBackSlash(
		AppDomain.CurrentDomain.DynamicDirectory ?? AppDomain.CurrentDomain.BaseDirectory));

**Comment by krgn** [comment] 2017-01-27 16:57
Hey, I created [PR #86](https://github.com/zeromq/clrzmq4/pull/86) to add the desired behavior on Windows and Posix systems. I tested this in my current project and it works well on Windows. Feedback welcome! (Btw. `AppDomain.CurrentDomain.DynamicDirectory` did not work as exepected, so I had to use `Assembly.GetExecutingAssembly().Location` instead)

**Comment by metadings** [comment] 2017-01-27 17:16
Yes, this is awesome.

I've just moved DllPath before Path on Posix systems, so you get your own version, before the installed version.

**Comment by krgn** [comment] 2017-01-27 17:16
Excellent! Thanks for including this :)

**Comment by glopesdev** [comment] 2017-02-19 20:03
I've hit upon the exact same edge case. However, in my case, it is even worse, because the plugin needs to load the native DLLs from the currently specified PATH environment variable.

It seems that all these problems stem from the fact that the code in [Platform.Win32.cs](https://github.com/zeromq/clrzmq4/blob/b5c900e99567b21c8c06b9648e881b43a0596b56/lib/Platform.Win32.cs) does not follow the [Dynamic-Link Library Search Order](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx) specified in the Microsoft guidelines.

As per those guidelines, directories specified in the PATH environment variable should be checked. If you really need the ZeroMQ CLR to load libraries by hand, then all paths specified in the platform guidelines should be included in the search to ensure correct and expected behavior.

Another (I would say preferred) way to ensure that everything behaves as expected is to avoid loading libraries manually in the first place. P/Invoke by itself already takes care of everything under the hood and will follow the proper library loading rules for each native implementation.

**Comment by krgn** [comment] 2017-02-22 07:24
@glopesdev I am not sure about Windows, but on Linux it could also check `LD_LIBRARY_PATH` as well, though I am unsure how it could distinguish between 64- and 32bit platforms.

**Comment by metadings** [comment] 2017-02-22 10:55
Yes, I'm doing so now, in [EnumeratePATH in Platform.Win32](https://github.com/zeromq/clrzmq4/blob/master/lib/Platform.Win32.cs#L178) and in [EnumerateLibLdPATH in Platform.Posix](https://github.com/zeromq/clrzmq4/blob/master/lib/Platform.Posix.cs#L288).

Do you want to try this, before I'm going live, with this, on nuget?

**Comment by glopesdev** [comment] 2017-06-22 07:32
@metadings Sorry for the long silence. I have just tried the modifications, but unfortunately they are still not compliant with Microsoft's DLL search order. The reason is that you are appending either an "amd64" or a "x64" suffix to the folders that are specified in the PATH.

There is no need to do this. If the user has specified a PATH, he gets to decide in which exact folders he wants the DLLs to be placed. The enumeration should try to find the DLL directly in the PATH folders, and not assume any fixed folder structure.

Related to this, I have noticed that the structure of the NuGet package is also not standard. Native DLLs should be placed inside the "build\native" folder in order to comply with the [NuGet framework name used for native build content](http://blog.nuget.org/20130426/native-support.html). Currently they are being placed directly inside the "build" folder. This should be easy to fix by changing a couple of paths in the nuspec file.

**Comment by sigiesec** [comment] 2017-06-28 08:19
@glopesdev Enumerating the PATH manually should not be necessary at all. A call to LoadLibrary("basename.dll") will automatically evaluate the PATH (and some other directories). In addition, it might make sense to try to load the DLL from custom folders, but these should not be related to the PATH. This applies similarly for the other platforms as well. Maybe @metadings has some more information why it is done the way it is implement right now.

**Comment by metadings** [comment] 2017-09-06 08:17
The method `Platform.SetupImplementation` is loading binary assembly files, directly in the static constructor, for example in `static Platform()`, just to do this *once* per process.

Example:

	public static partial class ZPollItems
	{
		static ZPollItems()
		{
			Platform.SetupImplementation(typeof(ZPollItems));
		} //...

	public static partial class ZPollItems
	{
		public static class Win32
		{ //...

	public static partial class ZPollItems
	{
		public static class Posix
		{ //...

On Windows, the method is loading `*.dll` from `PATH`, on Linux `lib*.so` from `LD_LIBRARY_PATH`,
but also from `~/amd64/`, `~/x64/` OR from `~/i386/`, `~/x86/` directories,
using specified `string[] Platform.LibraryPaths`.

The method `Platform.SetupImplementation` does also setup once per process `public static readonly` fields from class `Platform` to class `Platform.Win32` OR `Platform.Posix`.
For example, if you're going to *use* delegate field `Platform.LoadUnmanagedLibrary`, you actually *do use* `Platform.Win32.LoadUnmanagedLibrary` OR `Platform.Posix.LoadUnmanagedLibrary` instead.
For example, if you're going to *use* `string[]` field `Platform.LibraryPaths`, you actually *do use* `Platform.Win32.LibraryPaths` OR `Platform.Posix.LibraryPaths` instead.

---

` Platform.cs` (2017-09-06):

	public static partial class Platform
	{
		public static readonly string[] LibraryPaths;

		public delegate UnmanagedLibrary LoadUnmanagedLibraryDelegate(string libraryName);
		public static readonly LoadUnmanagedLibraryDelegate LoadUnmanagedLibrary;

		public static void SetupImplementation(Type platformDependant) //...

`Platform.Win32.cs` (2017-09-06):
 
	public static partial class Platform
	{
		public static class Win32
		{
			private const string LibraryName = "kernel32";

			public static readonly string[] LibraryPaths = new string[] {
				   @"{AppBase}\{Arch}\{Compiler}\{LibraryName}.dll",
				// @"{AppBase}\{Arch}\{Compiler}\{LibraryName}-*.dll",
				   @"{AppBase}\{Arch}\{LibraryName}.dll",
				   @"{DllPath}\{Arch}\{LibraryName}.dll",
				// @"{AppBase}\{Arch}\{LibraryName}-*.dll",
				   @"{System32}\{LibraryName}.dll",
				// @"{System32}\{LibraryName}-*.dll",
			};

			[DllImport(LibraryName, CharSet = CharSet.Auto, BestFitMapping = false, SetLastError = true)]
			private static extern SafeLibraryHandle LoadLibrary(string fileName);

			public static UnmanagedLibrary LoadUnmanagedLibrary(string libraryName) //...


`Platform.Posix.cs` (2017-09-06):

	public static partial class Platform
	{
		public static class Posix
		{
			private const CallingConvention CCCdecl = CallingConvention.Cdecl;

			private const string __Internal = "__Internal";

			// private const string LibraryName = "libdl";

			public static readonly string[] LibraryPaths = new string[] {
				"{AppBase}/{Arch}/{Compiler}/{LibraryName}.a",
				"{AppBase}/{Arch}/{Compiler}/{LibraryName}.a.*",
				"{AppBase}/{Arch}/{Compiler}/{LibraryName}.so",
				"{AppBase}/{Arch}/{Compiler}/{LibraryName}.so.*",
				"{AppBase}/{Arch}/{LibraryName}.a",
				"{AppBase}/{Arch}/{LibraryName}.a.*",
				"{AppBase}/{Arch}/{LibraryName}.so",
				"{AppBase}/{Arch}/{LibraryName}.so.*",
				"{DllPath}/{Arch}/{LibraryName}.a",
				"{DllPath}/{Arch}/{LibraryName}.a.*",
				"{DllPath}/{Arch}/{LibraryName}.so",
				"{DllPath}/{Arch}/{LibraryName}.so.*",
				"{Path}/{LibraryName}.a",
				"{Path}/{LibraryName}.a.*",
				"{Path}/{LibraryName}.so",
				"{Path}/{LibraryName}.so.*",
			};

			[DllImport(__Internal, CallingConvention = CCCdecl)]
			private static extern SafeLibraryHandle dlopen(IntPtr filename, int flags);

			public static UnmanagedLibrary LoadUnmanagedLibrary(string libraryName) //...

**Comment by glopesdev** [comment] 2017-09-06 17:40
@metadings I really don't understand why native dependency resolution needs to be made so complicated. Operating systems already take care of all of this stuff, and they have very clear laid out rules on how library loading should be done.

User libraries should avoid reinventing these dependency resolution schemes from scratch as much as possible. This will greatly increase cross-platform compatibility. Demand for this is only rising, and the growth in the number of platforms is increasing (ARM, Windows Universal, etc). It is impossible for a single library to take care of all the edge cases by itself.

It will make everyone's life easier (and the code for CLR ZMQ simpler) if you do not try to do the OS' job.

**Comment by metadings** [comment] 2017-09-07 09:43
> It is impossible for a single library to take care of all the edge cases by itself.

You are wrong. I can do so, and this is making life very much easier.

**Comment by glopesdev** [comment] 2017-09-07 17:40
Ok

**Comment by metadings** [comment] 2019-03-09 13:10
Closing this issue. It's too old - use [nuget/ZeroMQ v4.1.0.30](https://www.nuget.org/packages/ZeroMQ/4.1.0.30) or do `git clone https://github.com/zeromq/clrzmq4 && cd clrzmq4 && msbuild clrzmq4.mono.sln`

**Closed as completed by metadings** 2019-03-09 13:10 UTC
