### ISSUE TITLE
ROUTER socket cannot receive messages from DEALER if binding after connect

### ISSUE THREAD

**Issue by dumpvn** [zeromq/clrzmq4#152] opened 2018-01-30 05:46 UTC
I have a simple dealer connect to a router socket as below

```
static void Main(string[] args)
{
    using (var ctx = ZContext.Create())
    {
        using (var dealer = new ZSocket(ctx, ZSocketType.DEALER))
        {
            dealer.IdentityString = "testing";
            dealer.Connect("tcp://127.0.0.1:2223");
            while (true)
            {
                dealer.SendFrame(new ZFrame("hello"));
                Thread.Sleep(1000);
            }
        }
    }
}

static void Main(string[] args)
{
    using (var ctx = ZContext.Create())
    {
        using (var router = new ZSocket(ctx, ZSocketType.ROUTER))
        {
            router.Bind("tcp://*:2223");
            while (true)
            {
                var frame = router.ReceiveFrame();
                Console.WriteLine(frame.ToString());
            }
        }
    }
}

```
it will work only if router startup before dealer. I want it to work even if I start dealer first and router after that. What can I do?

Thank you.

**Comment by tozzi21** [comment] 2018-02-05 06:51
@sigiesec any idea if theres a bug in the wrapper? this is similar to issue #141

**Comment by VictorSFaria** [comment] 2018-04-15 14:58
The problem is not in the wrapper, I just compile the last version of libzmq and this issue was resolved.

**Comment by PDHCoder** [comment] 2018-06-22 12:43
I have the same problem with PUSH/PULL sockets. When I bind the PULL socket after connecting the PUSH socket, the PULL socket never receives a message.
If the source of the problem is indeed the underlying libzmq library, please change it in the NuGet packet.

**Comment by metadings** [comment] 2019-03-09 13:18
Closing this issue. It's too old - there was likely a problem with the native source of libzmq.dll/.so .

**Closed as completed by metadings** 2019-03-09 13:18 UTC
