### ISSUE TITLE
Fails to create ZContext under .net Core 3.0

### ISSUE THREAD

**Issue by vsharma-weedenprime** [zeromq/clrzmq4#178] opened 2019-05-20 13:14 UTC
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'ZeroMQ.lib.zmq' threw an exception.
  Source=ZeroMQ
  StackTrace:
   at ZeroMQ.ZContext..ctor()
   at MDSTestClient.Program.Main(String[] args) in C:\Users\vsharma\OneDrive - Weeden Prime\source\MarketDataService\MDSTestClient\MDSTestClient\Program.cs:line 2521

Inner Exception 1:
TypeInitializationException: The type initializer for 'ZeroMQ.ZSymbol' threw an exception.

Inner Exception 2:
FieldAccessException: Cannot set initonly static field 'EPERM' after type 'ZeroMQ.ZError' is initialized.

**Comment by mkermit** [comment] 2019-10-09 09:06
+1 not able to use with .net core 3.0. Are any plans to fix the issue? thanks

**Comment by cezarypiatekGC** [comment] 2019-12-18 07:52
This is caused by the fact that `ZeroMQ.ZSymbol.PickupConstantSymbols` is trying to set readonly fields on `ZeroMQ,ZError` using reflection. In dotnet core 3.0 it's not possible anymore. The fix seems to be quite straightforward by removing `readonly` keyword, but I have two questions:
- Why these fields are marked as readonly? https://github.com/zeromq/clrzmq4/blob/6f193f3993c7e2f42ba823c2a85a1e7ba597eda2/ZError.cs#L172
- Why these fields are initialized using reflection? https://github.com/zeromq/clrzmq4/blob/6f193f3993c7e2f42ba823c2a85a1e7ba597eda2/ZSymbol.cs#L36

**Closed as completed** 2019-12-21 09:43 UTC

**Comment by valbers** [comment] 2020-10-09 10:47
can you please release a patch version with this commit inside? Thank you.

**Comment by steveocrypto** [comment] 2021-02-04 22:49
Can you please release a patch on this?  Could really use it on a .Net 3.1 build.

**Comment by TYoungSL** [comment] 2021-10-01 01:07
_the heck_

**Comment by MarcAzar** [comment] 2024-02-21 09:58
Still an issue using ZeroMQ V4.1.0.31 on .Net 7

**Comment by cezarypiatekGC** [comment] 2024-02-22 14:20
This project seems to be dead. I would recommend migrating your projects to NetMQ (ZeroMq fully implemented in C# without native dependencies)

https://github.com/zeromq/netmq
